services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: "16g"
          cpus: "4.0"
        reservations:
          memory: "16g"
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 5s
      timeout: 10s
      retries: 5
    runtime: nvidia 
    networks:
      - llm-net


  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    restart: "no"
    deploy:
      resources:
        limits:
          memory: "16g"
          cpus: "4.0"
        reservations:
          memory: "16g"
    networks:
      - llm-net

volumes:
  ollama_data:
  
networks:
  llm-net:
    driver: bridge
