FROM nvidia/cuda:12.6.2-devel-ubuntu22.04

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates && \
    rm -rf /var/lib/apt/lists/*

# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 11434
ENV OLLAMA_HOST=0.0.0.0
ENTRYPOINT ["/entrypoint.sh"]
